const fs = require('fs')
const path = require('path')
const translations = require('./en')

const setFlattenedKeysAsValues = (data, prevPath) => {
  const flattened = {}
  Object.keys(data).forEach(key => {
    const v = data[key]
    if (Object(v) !== v) {
      flattened[key] = prevPath + key
    } else {
      flattened[key] = setFlattenedKeysAsValues(v, prevPath + key + '.')
    }
  })
  return flattened
}

const object = JSON.stringify(setFlattenedKeysAsValues(translations, ''), null, 2)
const fileContents = `///////////////////////////////////
// This file is automatically generated from the keys of 'en.json'
// Do not edit it manually as it will be overwritten at the next pull/merge
// If it gets out of sync with your translations, you can run 'yarn i18n' to update it

export const i18nKeys = ${object}
`
const jsFilePath = path.resolve(__dirname, 'i18nKeys.ts')
fs.writeFile(jsFilePath, fileContents, 'utf8', () => console.log('done'))
