// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuogzOjlVJ-C8F47HApQDJXux35cCWDY',
    appId: '1:109004766417:web:f135355abab546ca0f99f0',
    messagingSenderId: '109004766417',
    projectId: 'ivorysolarisdemoapp',
    authDomain: 'ivorysolarisdemoapp.firebaseapp.com',
    storageBucket: 'ivorysolarisdemoapp.appspot.com',
    measurementId: 'G-4K09QPC43L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdWck0_AIAjEzmVtAvtW8GK0lHQWNUN0',
    appId: '1:109004766417:android:8385f1c86092651d0f99f0',
    messagingSenderId: '109004766417',
    projectId: 'ivorysolarisdemoapp',
    storageBucket: 'ivorysolarisdemoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCykMsmlptN46fRqysVmARI3eOF7QoTbcI',
    appId: '1:109004766417:ios:1b1c4bcfd81469b60f99f0',
    messagingSenderId: '109004766417',
    projectId: 'ivorysolarisdemoapp',
    storageBucket: 'ivorysolarisdemoapp.appspot.com',
    iosClientId: '109004766417-qsq0tp0tg4ab3ojb0du3ine5v3f9l1pn.apps.googleusercontent.com',
    iosBundleId: 'com.thinslices.solarisdemo',
  );
}
